#!/bin/bash

LLVM_LIBS="$(llvm-config --components)"
LLVM_LIBS=$(echo $LLVM_LIBS | sed "s/ /;/g")
LLVM_LIBS=$(echo $LLVM_LIBS | sed "s/all-targets;//g")
rm -Rf build
mkdir build
cd build
paradiseo_path = $1
if [[ -n "$paradiseo_path" ]]; then
    cmake .. -G Ninja -DLLVM_COMPS=$(echo $LLVM_LIBS) -DCMAKE_MODULE_PATH='${paradiseo_path}'
else
    cmake .. -G Ninja -DLLVM_COMPS=$(echo $LLVM_LIBS) -DCMAKE_MODULE_PATH='~/ParadisEO-2.0/cmake/module/'
fi

